# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: auto deploy service

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "joelwmale/webhook-action"}'
          body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
